name: Dev build

on:
  push:
    branches: [ master ]
#    paths-ignore: [ '.**', 'Examples/**', '**.md' ]

env:
  PROJECT_PATH: src/WTelegramBot.csproj
  CONFIGURATION: Release
  RELEASE_NOTES: ${{ github.event.head_commit.message }}

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
      with:
        fetch-depth: 100
        submodules: true
    - name: Determine version
      run: |
        git fetch --depth=100 --tags
        DESCR_TAG=$(git describe --tags)
        COMMITS=${DESCR_TAG#*-}
        COMMITS=${COMMITS%-*}
        LAST_TAG=${DESCR_TAG%%-*}
        NEXT_VERSION=${LAST_TAG%.*}.$((${LAST_TAG##*.} + 1))-dev.$COMMITS
        RELEASE_VERSION=${{vars.RELEASE_VERSION}}-dev.$COMMITS
        if [[ "$RELEASE_VERSION" > "$NEXT_VERSION" ]] then VERSION=$RELEASE_VERSION; else VERSION=$NEXT_VERSION; fi
        echo Last tag: $LAST_TAG · Next version: $NEXT_VERSION · Release version: $RELEASE_VERSION · Build version: $VERSION
        echo "VERSION=$VERSION" >> $GITHUB_ENV
    - name: Setup .NET
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: 8.0.x
    - name: Pack
      run: dotnet pack $PROJECT_PATH --configuration $CONFIGURATION -p:Version=$VERSION "-p:ReleaseNotes=\"$RELEASE_NOTES\"" --output packages
    # - name: Upload artifact
    #   uses: actions/upload-artifact@v4
    #   with:
    #     name: packages
    #     path: packages/*.nupkg
    - name: Nuget push
      run: dotnet nuget push packages/*.nupkg --api-key ${{secrets.NUGETAPIKEY}} --skip-duplicate --source https://api.nuget.org/v3/index.json
    - name: Deployment Notification
      env:
        JSON: |
          {
              "status": "success", "complete": true, "commitMessage": ${{ toJSON(github.event.head_commit.message) }},
              "message": "{ \"commitId\": \"${{ github.sha }}\", \"buildNumber\": \"${{ env.VERSION }}\", \"repoName\": \"${{ github.repository }}\"}"
          }
      run: |
        curl -X POST -H "Content-Type: application/json" -d "$JSON" ${{ secrets.DEPLOYED_WEBHOOK }}
